DROP TABLE IF EXISTS medicine;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
	user_id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(40) NOT NULL,
	user_password VARCHAR(255)
);
	

CREATE TABLE medicine (
	medicine_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	medicine_name VARCHAR(40)  NOT NULL,
	medicine_note VARCHAR(500),
	medicine_count INTEGER,
	medicine_check boolean NOT NULL DEFAULT FALSE,
	medicine_check_morning boolean NOT NULL DEFAULT FALSE,
	medicine_check_daytime boolean NOT NULL DEFAULT FALSE,
	medicine_check_night boolean NOT NULL DEFAULT FALSE,
	user_id INTEGER REFERENCES users(user_id)
);